"""Add Freebie model

Revision ID: 18f1d7de9bb4
Revises: 9f1a9693bc3d
Create Date: 2025-05-25 21:37:15.503885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f1d7de9bb4'
down_revision = '9f1a9693bc3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###