"""Create companies, devs, and freebies tables

Revision ID: 3f9de8b849d9
Revises: 18f1d7de9bb4
Create Date: 2025-05-25 22:27:27.156435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9de8b849d9'
down_revision = '18f1d7de9bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###